CREATE TABLE BLOG_TBL(
	ID 		INT AUTO_INCREMENT PRIMARY KEY,
	TITLE		VARCHAR(50) NOT NULL,
	CONTENT	VARCHAR(1000) NOT NULL
);

INSERT INTO blog_tbl(TITLE, CONTENT) VALUES
('강사님 짱!!', '냉무'),
('내일은 불금이다', '즐기자'),
('배고프다', '마라탕~ 콜') ;

SELECT * FROM blog_tbl;

DROP TABLE BLOG_COMMENTS_TBL;

CREATE TABLE BLOG_COMMENTS_TBL(
	ID 		INT AUTO_INCREMENT PRIMARY KEY,
	COMMENT	VARCHAR(1000) NOT NULL,
	BLOG_ID  INT NOT NULL REFERENCES blog_tbl(ID)
);

SELECT *
FROM blog_comments_tbl;